### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-mochawesome-reporter#68]
Hey @fijijavis  ,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

We have been looking into successful WDIO plugins like this one as we want to ensure that its development can be continued even if the original maintainer decides to move on. Therefore on behalf of the WebdriverIO community I would like to ask if you would be interested to move this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by christian-bromann** [comment]
@fijijavis any comments?

**Comment by imvu-mriehle** [comment]
This has turned out to be an issue for us in our testing environment.  We can downgrade some packages to work around it for now. Is there anything we can do to move forward on this issue?

**Comment by christian-bromann** [comment]
@fijijavis any updates?

**Comment by talbss** [comment]
@fijijavis @christian-bromann any news on moving this project?
It is used by several people and deserve to be maintained. Thank you.

**Comment by christian-bromann** [comment]
@fijijavis hey, getting more requests about support on this package. Would love to give you a hand.

**Comment by testSadab** [comment]
@fijijavis report has been used by many and would be great if we move this to webdriverio to keep it updated.

**Comment by taninnazar** [comment]
@christian-bromann Hi, could you please have some influence on updating this reporter to get it working with the latest WDIO version? As it's developer doesn't respond anywhere. Thanks

**Comment by christian-bromann** [comment]
I have just ported his JSON reporter to the core repository: https://github.com/webdriverio/webdriverio/pull/11623. If you can make a similar PR that transforms the code base into TypeScript I am happy to merge it.

**Comment by taninnazar** [comment]
Hi @christian-bromann,  did you totally remove the link to wdio-mochawesome-reporter from the WDIO readme file? Does that mean you are not going to proceed with it?

**Comment by christian-bromann** [comment]
The reporter is still documented in the v7 docs: https://v7.webdriver.io/docs/wdio-mochawesome-reporter .. however according to #84 it is currently not supported in v8 so there is no point having it documented there. We would totally love to have a proper html reporter. Interested to contribute that?

**Comment by christian-bromann** [comment]
@jemishgopani I assume closing the issue means that you are not interested moving the repository in our community org? I think there is a lot of interest helping to maintain this package and that org could be a good place to do that. What do you think?

**Comment by jemishgopani** [comment]
Sorry, I didn't see this @christian-bromann yes we can move this to community org 👍

**Comment by christian-bromann** [comment]
Awesome, please see my comment above: https://github.com/jemishgopani/wdio-mochawesome-reporter/issues/68#issuecomment-953624703

**Comment by jemishgopani** [comment]
> Awesome, please see my comment above: [#68 (comment)](https://github.com/jemishgopani/wdio-mochawesome-reporter/issues/68#issuecomment-953624703)

Can you please invite me in org?

**Comment by christian-bromann** [comment]
Invite sent!

**Comment by jemishgopani** [comment]
Thanks, Repository successfully transferred.

**Comment by christian-bromann** [comment]
Awesome, thanks a lot!
